### ISSUE TITLE
Thaumcraft 6.0.BETA4 crashing when creating foci

### ISSUE THREAD

**Issue by zdepav** [Azanor/thaumcraft-suggestions#182]
When placing effects / modifiers into the Focal Manipulator, the game crashes with the following error:

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at thaumcraft.api.casters.FocusHelper.canPartsConnect(FocusHelper.java:66)
	at thaumcraft.client.gui.GuiFocalManipulator.func_73863_a(GuiFocalManipulator.java:222)

**Comment by MCShammer** [comment]
This is the suggestion page, not for thaumcraft 6 bug reports.
