### ISSUE TITLE
Crash with forge 2768, regressing forge to 2705 fixes crash.

### ISSUE THREAD

**Issue by jgilmore** [Azanor/thaumcraft-suggestions#446]
Forge bug? Maybe. IDK, but I couldn't find anything anywhere about this issue, so figured I'd post it here.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class thaumcraft.common.lib.crafting.ThaumcraftCraftingManager
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getPotionReagentsRecursive(ThaumcraftCraftingManager.java:337)
	at thaumcraft.common.config.ConfigAspects.getPotionAspects(ConfigAspects.java:692)
	at thaumcraft.common.config.ConfigAspects.registerItemAspects(ConfigAspects.java:525)
	at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:36)
	at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:82)
	at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:54)
	at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-34-generic
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 189345304 bytes (180 MB) / 513015808 bytes (489 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -Xmx4G -Xmx4G -Xmn128M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version      | Source                           | Signature                                |
	|:------ |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJ  | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJ  | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge      | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar           | None                                     |
	| UCHIEE | thaumcraft | 6.1.BETA25   | Thaumcraft-1.12.2-6.1.BETA25.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 396.54' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
[19:25:49] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /home/jgilmore/.technic/modpacks/12herb/crash-reports/crash-2018-10-07_19.25.49-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by wamc2017** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/1468
